/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.general;

/**
 *
 * @author lenovo
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
public class AjouterEntree extends javax.swing.JPanel {

    /**
     * Creates new form AjouterEntree
     */
    public AjouterEntree() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomProduit = new javax.swing.JLabel();
        quantiteProduit = new javax.swing.JLabel();
        nomProduitD = new javax.swing.JTextField();
        quantiteProduitD = new javax.swing.JTextField();
        AjouterProduit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        nomProduit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomProduit.setText("Nom Produit :");

        quantiteProduit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quantiteProduit.setText("Quantité Produit :");

        nomProduitD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomProduitDActionPerformed(evt);
            }
        });

        quantiteProduitD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantiteProduitDActionPerformed(evt);
            }
        });

        AjouterProduit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AjouterProduit.setText("Ajouter");
        AjouterProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterProduitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quantiteProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomProduitD)
                    .addComponent(quantiteProduitD)
                    .addComponent(AjouterProduit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addComponent(nomProduitD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nomProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(quantiteProduitD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjouterProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantiteProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nomProduitDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomProduitDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomProduitDActionPerformed

    private void quantiteProduitDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantiteProduitDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantiteProduitDActionPerformed

    private void AjouterProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterProduitActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            // database is my_tutorial, userid =root, password //
            // Update your usrid, password and database name //
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/gestionstock","root","");
            Statement st=con.createStatement();

            // Adding record
            String query1="INSERT INTO `produit`"
            + " (`nom_produit`, `qantit_produit`)"
            + "VALUES('" +nomProduitD.getText()+"','"+quantiteProduitD.getText()+"')";

            st.execute(query1); // record added.

            con.close();

        }catch(Exception e){ System.out.println(e);}
        //////////////////////////////

    }//GEN-LAST:event_AjouterProduitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterProduit;
    private javax.swing.JLabel nomProduit;
    private javax.swing.JTextField nomProduitD;
    private javax.swing.JLabel quantiteProduit;
    private javax.swing.JTextField quantiteProduitD;
    // End of variables declaration//GEN-END:variables
}
