/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.general;

import com.model.Produit;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import utils.ConnectionDB;
public class ConsulterSorties extends javax.swing.JPanel {
    public static int x=0;

    /**
     * Creates new form ConsulterEntrees
     */
    public ConsulterSorties() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomProduit = new javax.swing.JLabel();
        nomProduitD = new javax.swing.JTextField();
        quantiteProduit = new javax.swing.JLabel();
        quantiteProduitD = new javax.swing.JTextField();
        AjouterProduit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEntres = new javax.swing.JTable();
        consulterEntres = new javax.swing.JButton();
        AjouterProduit1 = new javax.swing.JButton();
        deleteProduit = new javax.swing.JButton();
        AjouterProduit4 = new javax.swing.JButton();

        nomProduit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomProduit.setText("Nom Sortie:");

        nomProduitD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomProduitDActionPerformed(evt);
            }
        });

        quantiteProduit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quantiteProduit.setText("Quantité Sortie:");

        quantiteProduitD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantiteProduitDActionPerformed(evt);
            }
        });

        AjouterProduit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AjouterProduit.setText("Modifier ");
        AjouterProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterProduitActionPerformed(evt);
            }
        });

        tableEntres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nom Sortie", "Quantite Sortie"
            }
        ));
        tableEntres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEntresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEntres);

        consulterEntres.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        consulterEntres.setText("Consulter");
        consulterEntres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulterEntresActionPerformed(evt);
            }
        });

        AjouterProduit1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AjouterProduit1.setText("Ajouter");
        AjouterProduit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterProduit1ActionPerformed(evt);
            }
        });

        deleteProduit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteProduit.setText("Supprimer");
        deleteProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProduitActionPerformed(evt);
            }
        });

        AjouterProduit4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AjouterProduit4.setText("Actualiser ");
        AjouterProduit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterProduit4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(AjouterProduit1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(deleteProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(AjouterProduit4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(consulterEntres, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantiteProduit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomProduitD, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantiteProduitD, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AjouterProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AjouterProduit4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consulterEntres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AjouterProduit1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomProduitD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantiteProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantiteProduitD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(AjouterProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nomProduitDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomProduitDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomProduitDActionPerformed

    private void quantiteProduitDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantiteProduitDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantiteProduitDActionPerformed

    private void AjouterProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterProduitActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            // database is my_tutorial, userid =root, password //
            // Update your usrid, password and database name //
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/gestionstock","root","");
            Statement st=con.createStatement();

            // Adding record
            String query1="INSERT INTO `produit`"
            + " (`nom_produit`, `qantit_produit`)"
            + "VALUES('" +nomProduitD.getText()+"','"+quantiteProduitD.getText()+"')";

            st.execute(query1); // record added.

            con.close();

        }catch(Exception e){ System.out.println(e);}
        //////////////////////////////
    }//GEN-LAST:event_AjouterProduitActionPerformed

    private void consulterEntresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulterEntresActionPerformed
        try{
            DefaultTableModel tableModelEntres= (DefaultTableModel)tableEntres.getModel();
            List<Produit> products = new ArrayList<>();
            Class.forName("com.mysql.cj.jdbc.Driver");
            // database is my_tutorial, userid =root, password //
            // Update your usrid, password and database name //
            Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/gestionstock","root","");
            Statement st=con.createStatement();

            // Adding record
            String sql="select * from  produit";
            ResultSet  resultat = st.executeQuery(sql);
            while(resultat.next()){
                int id = resultat.getInt("id");
                String nomProduit = resultat.getString("nom_produit");
                String qantiteProduit = resultat.getString("qantit_produit");
                Produit produit= new Produit();
                produit.setId(id);
                produit.setNomProduit(nomProduit);
                produit.setQuantiteProduit(qantiteProduit);
                products.add(produit);
                // Produit tableEntre[]={produit.class};

            }
            for (int i = 0; i < products.size(); i++) {
                tableModelEntres.insertRow(i, new Object[] {
                    products.get(i).getId(),
                    products.get(i).getNomProduit(),
                    products.get(i).getQuantiteProduit(),

                });
            }

            con.close();

        }catch(Exception e){ System.out.println(e);}
    }//GEN-LAST:event_consulterEntresActionPerformed

    private void AjouterProduit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterProduit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AjouterProduit1ActionPerformed

    private void deleteProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProduitActionPerformed
    // String  id = String.ValueOf(tableEntres.getValueAt(tableEntres.getSelectedRow(), 0));
    
         
    }//GEN-LAST:event_deleteProduitActionPerformed

    private void AjouterProduit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterProduit4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AjouterProduit4ActionPerformed

    private void tableEntresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEntresMouseClicked
    nomProduitD.setText((String) tableEntres.getValueAt(tableEntres.getSelectedRow(), 1));
    quantiteProduitD.setText((String) tableEntres.getValueAt(tableEntres.getSelectedRow(), 2));
    }//GEN-LAST:event_tableEntresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterProduit;
    private javax.swing.JButton AjouterProduit1;
    private javax.swing.JButton AjouterProduit4;
    private javax.swing.JButton consulterEntres;
    private javax.swing.JButton deleteProduit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomProduit;
    private javax.swing.JTextField nomProduitD;
    private javax.swing.JLabel quantiteProduit;
    private javax.swing.JTextField quantiteProduitD;
    private javax.swing.JTable tableEntres;
    // End of variables declaration//GEN-END:variables
}
