/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frameConsultation;

import com.model.Produit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import utils.ConnectionDB;

/**
 *
 * @author lenovo
 */
public class listeEntres extends javax.swing.JFrame {

    /**
     * Creates new form listeEntres
     */
    public listeEntres() {
        initComponents();
        listeSortie();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEntres = new javax.swing.JTable();
        consulterEntres = new javax.swing.JButton();
        sortie = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableEntres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nom_produit", "qantit_produit"
            }
        ));
        jScrollPane1.setViewportView(tableEntres);

        consulterEntres.setText("Consulter");
        consulterEntres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulterEntresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(consulterEntres)
                .addGap(67, 67, 67)
                .addComponent(sortie, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consulterEntres)
                    .addComponent(sortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void listeSortie(){
         try{  
	ConnectionDB connectionDB = new ConnectionDB();
        Connection con=connectionDB.getConnection();
	Statement st=con.createStatement();  
	
	// Adding record 
	String sql="select * from  produit";
        ResultSet  resultat = st.executeQuery(sql); 
        while(resultat.next()){ 
        String nomProduit = resultat.getString("nom_produit"); 
        sortie.addItem(nomProduit);
        
        }
	
	con.close();  
	
}catch(Exception e){ System.out.println(e);} 
    	
    }
    private void consulterEntresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulterEntresActionPerformed
        try{
        DefaultTableModel tableModelEntres= (DefaultTableModel)tableEntres.getModel();
        List<Produit> products = new ArrayList<>();
	Class.forName("com.mysql.cj.jdbc.Driver");  
	// database is my_tutorial, userid =root, password //
       // Update your usrid, password and database name // 	
	Connection con=DriverManager.getConnection(  
	"jdbc:mysql://localhost:3306/gestionstock","root","");
	Statement st=con.createStatement();  
	
	// Adding record 
	String sql="select * from  produit";
        ResultSet  resultat = st.executeQuery(sql); 
        while(resultat.next()){ 
        int id = resultat.getInt("id"); 
        String nomProduit = resultat.getString("nom_produit"); 
        String qantiteProduit = resultat.getString("qantit_produit"); 
        Produit produit= new Produit();
        produit.setId(id);
        produit.setNomProduit(nomProduit);
        produit.setQuantiteProduit(qantiteProduit);
        products.add(produit);
       // Produit tableEntre[]={produit.class};
            
        }
         for (int i = 0; i < products.size(); i++) {
        tableModelEntres.insertRow(i, new Object[] {
        products.get(i).getId(),
        products.get(i).getNomProduit(),
        products.get(i).getQuantiteProduit(),
       
    });
  }
	
	con.close();  
	
}catch(Exception e){ System.out.println(e);} 
    	
    }//GEN-LAST:event_consulterEntresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listeEntres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listeEntres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listeEntres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listeEntres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listeEntres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consulterEntres;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> sortie;
    private javax.swing.JTable tableEntres;
    // End of variables declaration//GEN-END:variables
}
